-- 1.ユーザー
CREATE TABLE users (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	body VARCHAR(255),
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 2.キャラクター
CREATE TABLE characters (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	family_name VARCHAR(50) NOT NULL,
	first_name VARCHAR(50) NOT NULL,
	family_name_kana VARCHAR(50),
	first_name_kana VARCHAR(50),
	description VARCHAR(100),
	description_result VARCHAR(100),
	character_image_path VARCHAR(255),
	result_image_path VARCHAR(255)
);

-- 3.質問
CREATE TABLE questions (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	body VARCHAR(255),
	sort_order INT
);

-- 4.選択肢
CREATE TABLE choices (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	questions_id INT,
	characters_id INT,
	body VARCHAR(255),
	
	CONSTRAINT fk_choices_questions FOREIGN KEY (questions_id) REFERENCES questions (id) ON DELETE CASCADE,
	CONSTRAINT fk_choices_characters FOREIGN KEY (characters_id) REFERENCES characters (id) ON DELETE CASCADE
);

-- 5.診断結果
CREATE TABLE diagnosis_results (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	users_id BIGINT,
	characters_id INT NOT NULL,
	diagnosed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_results_users FOREIGN KEY (users_id) REFERENCES users (id),
	CONSTRAINT fk_results_characters FOREIGN KEY (characters_id) REFERENCES characters (id) ON DELETE CASCADE 
)