-- =====================================================
-- 1. ユーザー表 (users)
-- 役割：アプリを使う人の情報をしまう表（登録・表示・編集・削除の対象）
-- =====================================================
CREATE TABLE users (
    -- 【PK / 主キー】ユーザーを1人に特定するための欄（int/整数）
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- 【カラム】ユーザー名を入れる欄（string/文字列）
    username VARCHAR(100) NOT NULL,
    
    -- 【カラム】登録日時を自動記録する欄
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- =====================================================
-- 2. キャラクター表 (characters)
-- 役割：診断結果になる鬼滅のキャラの情報をしまう表
-- =====================================================
CREATE TABLE characters (
    -- 【PK / 主キー】キャラを1つに特定するための欄（int/整数）
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- 【カラム】キャラの名前（string/文字列）
    name VARCHAR(100) NOT NULL,
    
    -- 【カラム】キャラの説明（string/文字列）
    description TEXT NOT NULL,
    
    -- 【追加】結果説明（1000文字まで） 
     description_results VARCHAR(100) NOT NULL,
     
    -- 【カラム】キャラの画像の場所・URL（string/文字列）
    character_image_path VARCHAR(255) NOT NULL,
    
    -- 【追加】結果用キャラ画像
    result_image_path VARCHAR(255) NOT NULL 
);

-- =====================================================
-- 3. 質問表 (questions)
-- 役割：診断で画面に出す質問の文章をしまう表
-- =====================================================
CREATE TABLE questions (
    -- 【PK / 主キー】質問を1つに特定するための欄（int/整数）
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- 【カラム】質問の文章（string/文字列） 「例：休日は何をして過ごす？」
    body VARCHAR(255) NOT NULL
);

-- =====================================================
-- 4. 選択肢表 (choices)
-- 役割：各質問の答えの候補をしまう表
-- つながり：【質問 1】対【選択肢 多】（記号：||--o{ ）
-- =====================================================
CREATE TABLE choices (
    -- 【PK / 主キー】選択肢を1つに特定するための欄（int/整数）
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- 【FK / 外部キー】「どの質問のものか」を指す欄。質問表のidとつながる
    question_id INT NOT NULL,
    
    -- 【カラム】選択肢の文章（string/文字列） 「例：外で運動」
    body VARCHAR(255) NOT NULL,
    
    -- 【FK / 外部キー】「選ぶと1点入るキャラ」を直接指定する欄。キャラ表のidとつながる
    character_id INT NOT NULL, 
    
    -- 質問表（questions）との紐付け設定（質問が消えたら選択肢も消えるカスケード設定）
    CONSTRAINT fk_choices_question FOREIGN KEY (question_id) REFERENCES questions (id) ON DELETE CASCADE,
    
    -- キャラクター表（characters）との紐付け設定
    CONSTRAINT fk_choices_character FOREIGN KEY (character_id) REFERENCES characters (id)
);

-- =====================================================
-- 5. 診断結果表 (diagnosis_results)
-- 役割：誰が、どのキャラと診断されたかをしまう表（users と characters をつなぐ役目）
-- つながり：ユーザーが削除されたら、その結果も一緒に消える（カスケード削除）
-- =====================================================
CREATE TABLE diagnosis_results (
    -- 【PK / 主キー】診断結果データを1つに特定するための欄（int/整数）
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- 【FK / 外部キー】「誰が」を表す欄。ユーザー表のidとつながる
    user_id BIGINT NOT NULL,
    
    -- 【FK / 外部キー】「どのキャラになったか」を表す欄。キャラ表のidとつながる
    character_id INT NOT NULL,
    
    -- 【カラム】診断された日時を自動記録する欄
    diagnosed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    -- 【カスケード削除】ユーザー(users)が削除されたら、連動してこの診断結果も自動で消える設定
    CONSTRAINT fk_results_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    
    -- キャラクター表（characters）との紐付け設定
    CONSTRAINT fk_results_character FOREIGN KEY (character_id) REFERENCES characters (id)
);